const translations = {
    ru: {
      home: "Главная страница",
      aboutme: "Обо мне",
      aboutmeBannerTitle: "Привет, я Абдымалик!",
      aboutmeBannerText: "c +1 год опытом работы и 7+ пет-проектами",
      aboutmeBannerBold: "Frontend-разработчик",
      titleProjects: "Проекты",
      readCase: "Подробнее",
      bannerText1 : "Это кинопоисковое приложение, разработанное с использованием React.js для пользовательского интерфейса, Appwrite для бэкенд-сервисов и TailwindCSS для стилизации. Интеграция с TMDB API позволяет пользователям просматривать популярные фильмы, искать кинокартины и изучать контент. Приложение отличается адаптивным дизайном и современным визуальным оформлением.",
      projectSummaryText1 : "Просмотр фильмов:\n- Доступ к обширной библиотеке киноконтента.\nПоиск:\n- Интеллектуальный поисковой механизм по названиям.\nАлгоритм трендов:\n-  Динамическое отображение популярных фильмов на основе актуальных метрик.\nСовременный интерфейс:\n-  Продуманный UI/UX-дизайн.\nАдаптивность:\n-  Полноценная работа на всех типах устройствах.\nДополнительные преимущества включают продуманную архитектуру кода и высокую степень переиспользуемости компонентов.",
      bannerTitle: "Сайт для блоггинга",
      bannerText2 : "Веб-приложение блога с системой авторизации, функционалом публикации и удаления записей, а также взаимодействием через комментарии с оценками (лайки/дизлайки) и ветвлением обсуждений.",
      projectSummaryText2 : "Добро пожаловать в Blog Website — современную full-stack платформу для блогов, созданную на JavaScript, React, MongoDB, Redux и HTML/CSS. Наш сервис позволяет пользователям создавать, редактировать и удалять посты, оставлять комментарии, оценивать записи (лайки) и отвечать на комментарии. Независимо от того, вы автор или читатель, здесь каждый найдёт что-то для себя!",
      bannerText3 : "Этот проект — веб-страница, посвящённая криптовалютам. Она предоставляет актуальную информацию о ведущих криптовалютах, последние новости из мира криптоиндустрии и тенденции изменения цен на криптовалюты.",
      projectSummaryText3 : "Этот проект — веб-страница, посвящённая криптовалютам. Она предоставляет актуальную информацию о ведущих криптовалютах, последние новости из мира криптоиндустрии и тенденции изменения цен. Данные о новостях и ценах на криптовалюты получаются через REST API с использованием Express. На странице также реализован поиск новостей и график изменения цен с возможностью выбора периода.",
      bannerText4 : "Платформа для обмена изображениями с функциональностью, аналогичной Pinterest.",
      projectSummaryText4 : "Социальная платформа для обмена изображениями с функциональностью, похожей на Pinterest. На сайте реализована авторизация через Google. Пользователи могут сохранять и скачивать изображения, а также фильтровать их по категориям.",
      bannerText5 : "Современная платформа электронной коммерции в сфере электроники с интеграцией платежной системы Stripe и использованием Sanity CMS в качестве бэкенда.",
      projectSummaryText5 : "Современная платформа электронной коммерции в сфере электроники с интеграцией платежной системы Stripe и использованием Sanity CMS в качестве бэкенда.",
      bannerText6 : "Решение для управления файлами и совместного доступа, разработанное на Next.js 15 и Appwrite Node SDK с поддержкой современных функций для удобной работы с файлами.",
      projectSummaryText6 : "Аутентификация пользователей через Appwrite:\nРеализована система регистрации, входа и выхода с использованием механизмов аутентификации Appwrite.\n- Загрузка файлов. Возможность загрузки различных типов файлов: документов, изображений, видео и аудио с гарантией сохранности данных.\n- Просмотр и управление файлами. Просмотр загруженных файлов из хранилища Appwrite (с открытием в новой вкладке).\n- Переименование и удаление файлов. Скачивание файло. Мгновенный доступ к загруженным файлам через функцию скачивания.\n- Общий доступ к файла. Пользователи могут легко делиться файлами для совместной работы.\n- Интерактивная панель управления (Dashboard. Обзор используемого и общего объема хранилища. Последние загруженные файлы. Группировка файлов по типам. Глобальный поис. Мощный поиск по всем файлам и общему контенту на платформе.\n- Сортировка файлов. Гибкая организация файлов по дате, названию или размеру.\n- Современный адаптивный дизайн. Минималистичный UI с упором на удобство использования и кросс-платформенную совместимость.. Дополнительные возможност. Использование React 19 и Next.js 15. Интеграция с Appwrite Node SDK. Продуманная архитектура кода и переиспользуемые компоненты.",
      scopeName : "Вебсайт",
      scopeLink : "Посетить вебсайт",
      scopeLink2 : "Посетить GitHub",
      tools: "Технологический стек",
      testimonials: "Рекомендации",
      aboutmeHome:"Frontend-разработчик с опытом работы 1+ год. Стажировался в локальной компании Алматы и работал над поддержкой образовательного проекта. Создал 3+ модулей и пофиксил 20+ багов для оптимизации сайта на 40%. Работал над тасками бизнес-аналитиков на платформе Jira. Реализовал 5+ пет-проектов в которых использовал Next.js, REST API, Node.js(Express), MongoDB, Sanity, Appwrite, Telegram Bot, а также современных инструментов вроде MaterialUI, Ant-d, ShadCN и Tailwind CSS. Мои сильные стороны - самостоятельность в изучении (изучил Python на базовом уровне), умение расставлять приоритеты в задачах и поддержка коллег, когда у них слезы капают на клавиатуру. Больше всего люблю фронтенд за возможность получать мгновенный результат: создал - увидел - пощупал. Особенно люблю создавать и исправлять фичи, которыми я сам пользовался бы будучи пользователем. Ищу проект, где ощущается дух человечества, поливают зеленые умы собственным опытом и где “npm start“ запускает не только проект, но и хороший день. Взамен вырастет код который не будет стыдно показать своей маме.",
      serviceText1: "Нативный JavaScript в связке с API",
      serviceText2: "Связь фронтенда с Mongo, Sanity",
      serviceText3: "Создание целых компонентов и взаимосвязь между ними",
      serviceText4: "Redux — это небольшая библиотека с простым и ограниченным API, предназначенная для предсказуемого управления состоянием приложения.",
      serviceText5: "REST API — это общепринятый отраслевой стандарт для обмена данными между веб-сервисами.",
      serviceText6: "Next.js — современный фреймворк для создания высокопроизводительных React-приложений с серверным рендерингом и статической генерацией.",
      testimonialTitle: "Что говорят люди о моей работе?",
      testimonialName1: "Рано Хассанова",
      testimonialPosition1: "Куратор в ITC Bootcamp",
      tesitmonialText1: "Я обучала Малика во время его Bootcamp-программы и очень доволен его результатами. У него отличные коммуникативные навыки, что позволило мне эффективно обучать и работать с ним",
      testimonialName2: "Адилет Жанысбай",
      testimonialPosition2: "Ментор в Dara Solutions",
      tesitmonialText2: "Я очень рад, что он проходил стажировку в нашей компании, и могу сказать, что он показал выдающиеся результаты во время программы. Мы хотели предложить ему должность, но он решил приложить свои усилия в Стамбуле.",
      getintouch: "На связи",
      work: "Работа",
      available: "Доступен",
      dropaline: "Поработаем? Напиши мне",
      copyemail: "Скопировать почту",
      projectSummary: "Описание проекта",
      projectDetails: "Детали проекта",
      otherProjects: "Другие проекты",
      back: "Назад",
      resume: "Резюме",
      xp: "Опыт работы",
      edu: "Образование",
      softSkills: "Софтскилы",
      hardSkills: "Хардскилы",
      info1: "Разработал 3+ новых модулей для удобства и эффективности использования сотрудниками образовательных учреждений. Исправил 20+ багов. Реализовал Restful API между фронтендом и бэкендом, которое обеспечило стабильное взаимодействие. Работал с библиотеками formik, yup, uuid, i18next.",
      degree2: "Инженер ОТиТБ, Переводчик, Горный мастер",
      info2: "Контроль и организация горных работ, учет горного оборудования, обеспечение безопасности операций и эффективного процесса работ.",
      period1: "с июля по ноябрь 2024",
      period2: "c 2019 по 2024",
      period3: "с февраля по июнь 2024",
      period4: "c 2012 по 2019",
      place2: "Стамбульский Технический Университет",
      degree3: "Frontend разработка",
      degree4: "Горное дело",
      info3: "Курс включает обучение разработки клиентского и серверного ПО с использованием стека MERN (MongoDB, Express, React, Node.js), углублённое изучение HTML/CSS на препроцессорах SASS/SCSS, а также разработку Telegram-ботов.",
      info4: "В сфере горного дела — полный цикл работ: от открытой и подземной добычи до переработки полезных ископаемых",
      soft1: "Терпеливый", 
      soft2: "Стрессоустойчивый", 
      soft3: "Командная работа",
    },
    en: {
      home: "Home",
      aboutme: "About Me",
      aboutmeBannerTitle: "Hi, I'm Abdymalik!",
      aboutmeBannerText: "+1 year experience with 7+ pet projects",
      aboutmeBannerBold: "Frontend-developer",
      titleProjects: "Projects",
      readCase: "Read Case Study",
      bannerText1 : "Built with React.js for the user interface, Appwrite for backend services, and styled with TailwindCSS, this Movie App lets users browse trending movies, search titles, and explore content using the TMDB API. It features a responsive layout and a sleek, modern design.",
      projectSummaryText1 : "Browse All Movies: Explore a wide range of movies available on the platform. Search Movies: Easily search for specific movies using a search function. Trending Movies Algorithm: Displays trending movies based on a dynamic algorithm. Modern UI/UX: A sleek and user-friendly interface designed for a great experience. Responsiveness: Fully responsive design that works seamlessly across devices. and many more, including code architecture and reusability.",
      bannerTitle: "Blog website",
      bannerText2 : "Blog site with authorization, creating/deleting posts, comments, likes, dislikes, and replies.",
      projectSummaryText2 : "Welcome to Blog Website, a modern, full-stack blogging platform built with JavaScript, React, MongoDB, Redux, and HTML/CSS. This platform allows users to create, edit, and delete posts, comment on posts, like posts, and even reply to comments. Whether you're a blogger or a reader, this platform has something for everyone!",
      bannerText3 : "This project is a cryptocurrency-focused webpage that provides up-to-date information on top cryptocurrencies, the latest crypto news, and cryptocurrency price trends.",
      projectSummaryText3 : "This project is a cryptocurrency-focused webpage that provides up-to-date information on top cryptocurrencies, the latest crypto news, and cryptocurrency price trends. The data for news and cryptocurrency prices is fetched via a REST API using Express. The webpage also includes a news search function and a price chart with period selection.",
      bannerText4 : "A social image sharing platform with Pinterest-like functionality.",
      projectSummaryText4 : "A social image sharing platform with Pinterest-like functionality. Website has Google authorization. You can save and download pictures. You can filter images by categories.",
      bannerText5 : "Modern electronics e-commerce platform with Stripe payment integration and Sanity CMS backend.",
      projectSummaryText5 : "Modern electronics e-commerce platform with Stripe payment integration and Sanity CMS backend.",
      bannerText6 : "A storage management and file sharing platform that lets users effortlessly upload, organize, and share files. Built with the latest Next.js 15 and the Appwrite Node SDK, utilizing advanced features for seamless file management.",
      projectSummaryText6 : "User Authentication with Appwrite: Implement signup, login, and logout functionality using Appwrite's authentication system. FIle Uploads: Effortlessly upload a variety of file types, including documents, images, videos, and audio, ensuring all your important data. View and Manage Files: Users can browse through their uploaded files stored in Appwrite storage, view on a new tab, rename file or delete. Download Files: Users can download their uploaded files giving them instant access to essential documents. File Sharing: Users can easily share their uploaded files with others, enabling collaboration and easy access to important content. Dashboard: Gain insights at a glance with a dynamic dashboard that showcases total and consumed storage, recent uploads, and a summary of files grouped by type. Global Search: Users can quickly find files and shared content across the platform with a robust global search feature. Sorting Options: Organize files efficiently by sorting them by date, name, or size, making file management a breeze. Modern Responsive Design: A fresh and minimalist UI that emphasizes usability, ensuring a clean aesthetic across all device. And many more, including the latest React 19, Next.js 15 and Appwrite features alongside code architecture and reusability",
      bannerText7: "A modern travel agency platform with an admin dashboard and public site. Generate AI-powered trip itineraries based on country, travel style, interests, group type, and budget — and book trips with ease.",
      projectSummaryText7: "Features of the Travel Agency Project: AI-powered trip itinerary generator. Trip booking functionality on the public website. Admin dashboard with trip and user management. User growth metrics and trip analytics. Interactive charts and trip statistics table. Detailed trip overview. Responsive UI with a modern design. Secure user authentication and data management. Modular code architecture with reusable componen. and many more, built for scalability and a smooth user experience.",
      scopeName : "Website",
      scopeLink : "Visit website",
      scopeLink2 : "Visit GitHub",
      tools: "Tools",
      testimonials: "Testimonials",
      aboutmeHome: "Junior Frontend Developer with 1+ year of experience. Built 5 pet projects using API, Express, MongoDB, Sanity, Telegram Bot, and modern tools like Material UI, Ant Design, and Tailwind CSS. My strengths include self-driven learning (picked up Python at a basic level independently), task prioritization, and being the teammate who hands out tissues when someone’s stress tears drop to the keyboard.",
      serviceText1: "Javascript native, combining with API",
      serviceText2: "Connecting frontend and Sanity, MongooDB.",
      serviceText3: "Constructing whole page by components and provided with each other.",
      serviceText4: "Redux is a small library with a simple, limited API designed to be a predictable container for application state.",
      serviceText5: "REST APIs are an industry-standard way for web services to send and receive data.",
      serviceText6: "Next.js is the industry-leading React framework for building server-rendered, static, and hybrid web applications.",
      testimonialTitle: "What People Are Saying About My Work",
      testimonialName1: "Rano Khassanova",
      testimonialPosition1: "Curator at ITC Bootcamp",
      tesitmonialText1: "I teached Malik during his Bootcamp program and I am delighted with his results. He has excellent communication skills and uses robust workflows that allowed me to teach and work with him efficiently.",
      testimonialName2: "Adilet Zhanysbay",
      testimonialPosition2: "Mentor at Dara Solutions",
      tesitmonialText2: "I was glad to had him as an intern in our company and all I can say about him is that he showed outstanding performance during the internship program. We would like to offer him position but he wanted to conribute his efforts in Istanbul.",
      getintouch: "Get In Touch",
      work: "Work",
      available: "Available for Work",
      dropaline: "Interested in working together? Drop me a line",
      copyemail: "Copy email",
      projectSummary: "Project Summary",
      projectDetails: "Project Details",
      otherProjects: "Other Projects",
      back: "Back To Home",
      resume: "Resume",
      xp: "Work Experience",
      edu: "Education",
      softSkills: "Soft Skills",
      hardSkills: "Hard Skills",
      info1: "Developed 5+ new modules to improve usability and efficiency for educational staff. Fixed 30+ bugs, enhancing system stability and performance. Implemented a RESTful API between frontend and backend, ensuring seamless data interaction. Worked with Formik, Yup, UUID, and i18next",
      degree2: "HSE Engineer, Translator, Shift boss",
      info2: "Supervising mining operations, organizing worker pools and accounting for mining equipment, ensuring operational safety and efficient workflow.",
      period1: "July to Nov 2024",
      period2: "2019 to 2024",
      period3: "Feb to Jun, 2024",
      period4: "2012 to 2019",
      place2: "Istanbul Technical University",
      degree3: "Frontend development",
      degree4: "Mining Engineering",
      info3: "Program inculdes client and server software development using MERN bundle, mastering HTML/CSS on SASS/SCSS and Telegram Bot development.",
      info4: "Surface and underground mining that includes whole process starting with mining and ending with mineral processing.",
      soft1: "Hard and patient worker", 
      soft2: "Stress tolerant", 
      soft3: "Team worker",
    }
}

export default translations;