const translations = {
    ru: {
      home: "Главная страница",
      aboutme: "Обо мне",
      aboutmeBannerTitle: "Привет, я Абдымалик!",
      aboutmeBannerText: "c +1 год опытом работы и пет-проектами",
      aboutmeBannerBold: "Frontend-разработчик",
      titleProjects: "Проекты",
      readCase: "Подробнее",
      bannerText1 : "Чистый и адаптивный сайт, созданный на HTML, CSS и JavaScript. Проект демонстрирует лаконичный и элегантный дизайн, идеально подходящий для презентации продукта, услуги или компании.",
      projectSummaryText1 : "Оптимизированный для всех экранов - десктопы, планшеты и мобильные устройства. Интерактивные элементы на JavaScript: слайдер (swiper), аккордеон и модальные окна. Чистый современный дизайн с соблюдением принципов UI/UX. Протестировано и корректно работает во всех основных браузерах.",
      bannerTitle: "Сайт для блоггинга",
      bannerText2 : "Веб-приложение блога с системой авторизации, функционалом публикации и удаления записей, а также взаимодействием через комментарии с оценками (лайки/дизлайки) и ветвлением обсуждений.",
      projectSummaryText2 : "Добро пожаловать в Blog Website — современную full-stack платформу для блогов, созданную на JavaScript, React, MongoDB, Redux и HTML/CSS. Наш сервис позволяет пользователям создавать, редактировать и удалять посты, оставлять комментарии, оценивать записи (лайки) и отвечать на комментарии. Независимо от того, вы автор или читатель, здесь каждый найдёт что-то для себя!",
      bannerText3 : "Этот проект — веб-страница, посвящённая криптовалютам. Она предоставляет актуальную информацию о ведущих криптовалютах, последние новости из мира криптоиндустрии и тенденции изменения цен на криптовалюты.",
      projectSummaryText3 : "Этот проект — веб-страница, посвящённая криптовалютам. Она предоставляет актуальную информацию о ведущих криптовалютах, последние новости из мира криптоиндустрии и тенденции изменения цен. Данные о новостях и ценах на криптовалюты получаются через REST API с использованием Express. На странице также реализован поиск новостей и график изменения цен с возможностью выбора периода.",
      bannerText4 : "Платформа для обмена изображениями с функциональностью, аналогичной Pinterest.",
      projectSummaryText4 : "Социальная платформа для обмена изображениями с функциональностью, похожей на Pinterest. На сайте реализована авторизация через Google. Пользователи могут сохранять и скачивать изображения, а также фильтровать их по категориям.",
      bannerText5 : "Современная платформа электронной коммерции в сфере электроники с интеграцией платежной системы Stripe и использованием Sanity CMS в качестве бэкенда.",
      projectSummaryText5 : "Современная платформа электронной коммерции в сфере электроники с интеграцией платежной системы Stripe и использованием Sanity CMS в качестве бэкенда.",
      bannerText6 : "Пара телеграм-ботов, работающих с валютой и QR-кодами.",
      projectSummaryText6 : "Боты используют API, получая информацию из внешних источников, помогают обменивать валюту и работать с ссылками через QR-код.",
      scopeName : "Вебсайт",
      scopeLink : "Посетить вебсайт",
      scopeLink2 : "Посетить GitHub",
      tools: "Технологический стек",
      testimonials: "Рекомендации",
      aboutmeHome:"Junior Frontend-разработчик с опытом работы 1+ год. Реализовал 5 пет-проектов в которых использовал API, Express, MongoDB, Sanity, Telegram Bot, а также современных инструментов вроде MaterialUI, Ant-d и Tailwind. Мои сильные стороны - самостоятельность в изучении (изучил Python на базовом уровне), умение расставлять приоритеты в задачах и поддержка коллег, когда у них слезы капают на клавиатуру. Больше всего люблю фронтенд за возможность получать мгновенный результат: создал - увидел - пощупал. Особенно люблю создавать и исправлять фичи, которыми я сам пользовался бы будучи пользователем. Ищу проект, где ощущается дух человечества, поливают зеленые умы собственным опытом и где “npm start“ запускает не только проект, но и хороший день. Взамен вырастет код который не будет стыдно показать своей маме.",
      serviceText1: "Нативный JavaScript в свяхке с API",
      serviceText2: "Связь фронтенда с Mongo, Sanity",
      serviceText3: "Создание целых компонентов и взаимосвязь между ними",
      serviceText4: "Redux — это небольшая библиотека с простым и ограниченным API, предназначенная для предсказуемого управления состоянием приложения.",
      testimonialTitle: "Что говорят люди о моей работе?",
      testimonialName1: "Рано Хассанова",
      testimonialPosition1: "Куратор в ITC Bootcamp",
      tesitmonialText1: "Я обучала Малика во время его Bootcamp-программы и очень доволен его результатами. У него отличные коммуникативные навыки, что позволило мне эффективно обучать и работать с ним",
      testimonialName2: "Адилет Жанысбай",
      testimonialPosition2: "Ментор в Dara Solutions",
      tesitmonialText2: "Я очень рад, что он проходил стажировку в нашей компании, и могу сказать, что он показал выдающиеся результаты во время программы. Мы хотели предложить ему должность, но он решил приложить свои усилия в Стамбуле.",
      getintouch: "На связи",
      work: "Работа",
      available: "Доступен",
      dropaline: "Поработаем? Напиши мне",
      copyemail: "Скопировать почту",
      projectSummary: "Описание проекта",
      projectDetails: "Детали проекта",
      otherProjects: "Другие проекты",
      back: "Назад",
      resume: "Резюме",
      xp: "Опыт работы",
      edu: "Образование",
      softSkills: "Софтскилы",
      hardSkills: "Хардскилы",
      info1: "Разработал +5 новых модулей для удобства и эффективности использования сотрудниками образовательных учреждений. Исправил 30+ багов. Реализовал Restful API между фронтендом и бэкендом, которое обеспечило стабильное взаимодействие. Работал с библиотеками formik, yup, uuid, i18next.",
      degree2: "Инженер ОТиТБ, Переводчик, Горный мастер",
      info2: "Контроль и организация горных работ, учет горного оборудования, обеспечение безопасности операций и эффективного процесса работ.",
      period1: "с июля по ноябрь 2024",
      period2: "c 2019 по 2024",
      period3: "с февраля по июнь 2024",
      period4: "c 2012 по 2019",
      place2: "Стамбульский Технический Университет",
      degree3: "Frontend разработка",
      degree4: "Горное дело",
      info3: "Курс включает обучение разработки клиентского и серверного ПО с использованием стека MERN (MongoDB, Express, React, Node.js), углублённое изучение HTML/CSS на препроцессорах SASS/SCSS, а также разработку Telegram-ботов.",
      info4: "В сфере горного дела — полный цикл работ: от открытой и подземной добычи до переработки полезных ископаемых",
      soft1: "Терпеливый", 
      soft2: "Стрессоустойчивый", 
      soft3: "Командная работа",
    },
    en: {
      home: "Home",
      aboutme: "About Me",
      aboutmeBannerTitle: "Hi, I'm Abdymalik!",
      aboutmeBannerText: "+1 year experience with pet projects",
      aboutmeBannerBold: "Frontend-developer",
      titleProjects: "Projects",
      readCase: "Read Case Study",
      bannerText1 : "A clean and responsive brand landing page built with pure HTML, CSS, and JavaScript. This project demonstrates a simple yet elegant design suitable for showcasing a product, service, or brand.",
      projectSummaryText1 : "Optimized for all screen sizes, including desktops, tablets, and mobile devices. Includes JavaScript-powered interactions such as a swiper, accordeon and modal functions. Focus on clean and modern UI/UX design principles. Tested and functional on major browsers.",
      bannerTitle: "Blog website",
      bannerText2 : "Blog site with authorization, creating/deleting posts, comments, likes, dislikes, and replies.",
      projectSummaryText2 : "Welcome to Blog Website, a modern, full-stack blogging platform built with JavaScript, React, MongoDB, Redux, and HTML/CSS. This platform allows users to create, edit, and delete posts, comment on posts, like posts, and even reply to comments. Whether you're a blogger or a reader, this platform has something for everyone!",
      bannerText3 : "This project is a cryptocurrency-focused webpage that provides up-to-date information on top cryptocurrencies, the latest crypto news, and cryptocurrency price trends.",
      projectSummaryText3 : "This project is a cryptocurrency-focused webpage that provides up-to-date information on top cryptocurrencies, the latest crypto news, and cryptocurrency price trends. The data for news and cryptocurrency prices is fetched via a REST API using Express. The webpage also includes a news search function and a price chart with period selection.",
      bannerText4 : "A social image sharing platform with Pinterest-like functionality.",
      projectSummaryText4 : "A social image sharing platform with Pinterest-like functionality. Website has Google authorization. You can save and download pictures. You can filter images by categories.",
      bannerText5 : "Modern electronics e-commerce platform with Stripe payment integration and Sanity CMS backend.",
      projectSummaryText5 : "Modern electronics e-commerce platform with Stripe payment integration and Sanity CMS backend.",
      bannerText6 : "Pair of telegram bots that can work on currency and qr-code",
      projectSummaryText6 : "Telegram bots with API that takes information from outsource and exchange your money.",
      scopeName : "Website",
      scopeLink : "Visit website",
      scopeLink2 : "Visit GitHub",
      tools: "Tools",
      testimonials: "Testimonials",
      aboutmeHome: "Junior Frontend Developer with 1+ year of experience. Built 5 pet projects using API, Express, MongoDB, Sanity, Telegram Bot, and modern tools like Material UI, Ant Design, and Tailwind CSS. My strengths include self-driven learning (picked up Python at a basic level independently), task prioritization, and being the teammate who hands out tissues when someone’s stress tears drop to the keyboard.",
      serviceText1: "Javascript native, combining with API",
      serviceText2: "Connecting frontend and Sanity, MongooDB.",
      serviceText3: "Constructing whole page by components and provided with each other.",
      serviceText4: "Redux is a small library with a simple, limited API designed to be a predictable container for application state.",
      testimonialTitle: "What People Are Saying About My Work",
      testimonialName1: "Rano Khassanova",
      testimonialPosition1: "Curator at ITC Bootcamp",
      tesitmonialText1: "I teached Malik during his Bootcamp program and I am delighted with his results. He has excellent communication skills and uses robust workflows that allowed me to teach and work with him efficiently.",
      testimonialName2: "Adilet Zhanysbay",
      testimonialPosition2: "Mentor at Dara Solutions",
      tesitmonialText2: "I was glad to had him as an intern in our company and all I can say about him is that he showed outstanding performance during the internship program. We would like to offer him position but he wanted to conribute his efforts in Istanbul.",
      getintouch: "Get In Touch",
      work: "Work",
      available: "Available for Work",
      dropaline: "Interested in working together? Drop me a line",
      copyemail: "Copy email",
      projectSummary: "Project Summary",
      projectDetails: "Project Details",
      otherProjects: "Other Projects",
      back: "Back To Home",
      resume: "Resume",
      xp: "Work Experience",
      edu: "Education",
      softSkills: "Soft Skills",
      hardSkills: "Hard Skills",
      info1: "Developed 5+ new modules to improve usability and efficiency for educational staff. Fixed 30+ bugs, enhancing system stability and performance. Implemented a RESTful API between frontend and backend, ensuring seamless data interaction. Worked with Formik, Yup, UUID, and i18next",
      degree2: "HSE Engineer, Translator, Shift boss",
      info2: "Supervising mining operations, organizing worker pools and accounting for mining equipment, ensuring operational safety and efficient workflow.",
      period1: "July to Nov 2024",
      period2: "2019 to 2024",
      period3: "Feb to Jun, 2024",
      period4: "2012 to 2019",
      place2: "Istanbul Technical University",
      degree3: "Frontend development",
      degree4: "Mining Engineering",
      info3: "Program inculdes client and server software development using MERN bundle, mastering HTML/CSS on SASS/SCSS and Telegram Bot development.",
      info4: "Surface and underground mining that includes whole process starting with mining and ending with mineral processing.",
      soft1: "Hard and patient worker", 
      soft2: "Stress tolerant", 
      soft3: "Team worker",
    }
}

export default translations;